# Container App Deploy Template - Single Responsibility: Deploy container to Azure Container Apps
parameters:
- name: environment
  type: string
- name: imageTag
  type: string
- name: serviceConnection
  type: string

steps:
- task: AzureCLI@2
  displayName: 'Update Container App'
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get environment-specific values from Key Vault
      RESOURCE_GROUP="rg-containerapp-${{ parameters.environment }}-aue"
      CONTAINER_APP_NAME="ca-api-${{ parameters.environment }}-aue"
      ACR_NAME="$(acrName)"
      IMAGE_NAME="$ACR_NAME.azurecr.io/$(imageRepository):${{ parameters.imageTag }}"
      
      echo "Deploying $IMAGE_NAME to $CONTAINER_APP_NAME in $RESOURCE_GROUP"
      
      # Update container app with new image - declarative approach
      az containerapp update \
        --name $CONTAINER_APP_NAME \
        --resource-group $RESOURCE_GROUP \
        --image $IMAGE_NAME \
        --output table
      
      # Verify deployment
      az containerapp show \
        --name $CONTAINER_APP_NAME \
        --resource-group $RESOURCE_GROUP \
        --query "properties.latestRevisionName" \
        --output tsv